// <auto-generated />
namespace MVC5_DDD_EF_NINJECT.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NomeDaMigracao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NomeDaMigracao));
        
        string IMigrationMetadata.Id
        {
            get { return "201808262048315_NomeDaMigracao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
